
name: Localhost8080

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP'
        default: 'localhost'
        required: true

jobs:
    localhost8080:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run robot
          run: |
            mkdir reports
        - name: Run a localhost server
          run: |
            nohup python serv.py &
            sleep 5
            sudo netstat -tlnp
            curl -v http://localhost:8080
        - name: Run robot
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tasks:/opt/robotframework/tests:Z \
              -v ${PWD}/reports/file://opt/robotframework/temp/reports/file/ \
              -e ROBOT_OPTIONS="--variable LOCALHOST:${{ github.event.inputs.ip }}" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload run results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
