
name: Localhost8080

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    localhost8080:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Connect to localhost
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tasks:/opt/robotframework/tests:Z \
              -v ${PWD}/reports/file://opt/robotframework/temp/reports/file/ \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload run results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
